/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module async_fifo(wclk, wrst_n, winc, wdata, wfull, awfull, rclk, rrst_n, rinc, rdata, rempty, arempty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  output arempty;
  wire arempty;
  output awfull;
  wire awfull;
  wire [7:0] \fifomem.mem[0] ;
  wire [7:0] \fifomem.mem[10] ;
  wire [7:0] \fifomem.mem[11] ;
  wire [7:0] \fifomem.mem[12] ;
  wire [7:0] \fifomem.mem[13] ;
  wire [7:0] \fifomem.mem[14] ;
  wire [7:0] \fifomem.mem[15] ;
  wire [7:0] \fifomem.mem[1] ;
  wire [7:0] \fifomem.mem[2] ;
  wire [7:0] \fifomem.mem[3] ;
  wire [7:0] \fifomem.mem[4] ;
  wire [7:0] \fifomem.mem[5] ;
  wire [7:0] \fifomem.mem[6] ;
  wire [7:0] \fifomem.mem[7] ;
  wire [7:0] \fifomem.mem[8] ;
  wire [7:0] \fifomem.mem[9] ;
  wire [3:0] \fifomem.raddr ;
  wire [3:0] \fifomem.waddr ;
  input rclk;
  wire rclk;
  output [7:0] rdata;
  wire [7:0] rdata;
  output rempty;
  wire rempty;
  input rinc;
  wire rinc;
  wire \rptr_empty.arempty_val ;
  wire [4:0] \rptr_empty.rbin ;
  wire [4:0] \rptr_empty.rbinnext ;
  wire \rptr_empty.rempty_val ;
  wire [4:0] \rptr_empty.rgraynext ;
  wire [4:0] \rptr_empty.rptr ;
  wire [4:0] \rptr_empty.rq2_wptr ;
  input rrst_n;
  wire rrst_n;
  wire [4:0] \sync_r2w.wq1_rptr ;
  wire [4:0] \sync_r2w.wq2_rptr ;
  wire [4:0] \sync_w2r.rq1_wptr ;
  wire [4:0] \sync_w2r.wptr ;
  input wclk;
  wire wclk;
  input [7:0] wdata;
  wire [7:0] wdata;
  output wfull;
  wire wfull;
  input winc;
  wire winc;
  wire \wptr_full.awfull_val ;
  wire [4:0] \wptr_full.wbinnext ;
  wire \wptr_full.wfull_val ;
  wire [4:0] \wptr_full.wgraynext ;
  input wrst_n;
  wire wrst_n;
  sky130_fd_sc_hd__nor2b_1 _250_ (
    .A(wfull),
    .B_N(winc),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand3b_1 _251_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [0]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand3b_1 _252_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [1]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor4bb_1 _253_ (
    .A(wfull),
    .B(\fifomem.waddr [0]),
    .C_N(\fifomem.waddr [1]),
    .D_N(winc),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand3b_1 _254_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [2]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand3b_1 _255_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [3]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor4bb_1 _256_ (
    .A(wfull),
    .B(\fifomem.waddr [2]),
    .C_N(\fifomem.waddr [3]),
    .D_N(winc),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(_131_),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__and2_0 _258_ (
    .A(wdata[0]),
    .B(_128_),
    .X(_136_)
  );
  sky130_fd_sc_hd__mux2_1 _259_ (
    .A0(_136_),
    .A1(\fifomem.mem[10] [0]),
    .S(_135_),
    .X(_000_)
  );
  sky130_fd_sc_hd__and2_0 _260_ (
    .A(wdata[1]),
    .B(_128_),
    .X(_137_)
  );
  sky130_fd_sc_hd__mux2_1 _261_ (
    .A0(_137_),
    .A1(\fifomem.mem[10] [1]),
    .S(_135_),
    .X(_001_)
  );
  sky130_fd_sc_hd__and2_0 _262_ (
    .A(wdata[2]),
    .B(_128_),
    .X(_138_)
  );
  sky130_fd_sc_hd__mux2_1 _263_ (
    .A0(_138_),
    .A1(\fifomem.mem[10] [2]),
    .S(_135_),
    .X(_002_)
  );
  sky130_fd_sc_hd__and2_0 _264_ (
    .A(wdata[3]),
    .B(_128_),
    .X(_139_)
  );
  sky130_fd_sc_hd__mux2_1 _265_ (
    .A0(_139_),
    .A1(\fifomem.mem[10] [3]),
    .S(_135_),
    .X(_003_)
  );
  sky130_fd_sc_hd__and2_0 _266_ (
    .A(wdata[4]),
    .B(_128_),
    .X(_140_)
  );
  sky130_fd_sc_hd__mux2_1 _267_ (
    .A0(_140_),
    .A1(\fifomem.mem[10] [4]),
    .S(_135_),
    .X(_004_)
  );
  sky130_fd_sc_hd__and2_0 _268_ (
    .A(wdata[5]),
    .B(_128_),
    .X(_141_)
  );
  sky130_fd_sc_hd__mux2_1 _269_ (
    .A0(_141_),
    .A1(\fifomem.mem[10] [5]),
    .S(_135_),
    .X(_005_)
  );
  sky130_fd_sc_hd__and2_0 _270_ (
    .A(wdata[6]),
    .B(_128_),
    .X(_142_)
  );
  sky130_fd_sc_hd__mux2_1 _271_ (
    .A0(_142_),
    .A1(\fifomem.mem[10] [6]),
    .S(_135_),
    .X(_006_)
  );
  sky130_fd_sc_hd__and2_0 _272_ (
    .A(wdata[7]),
    .B(_128_),
    .X(_143_)
  );
  sky130_fd_sc_hd__mux2_1 _273_ (
    .A0(_143_),
    .A1(\fifomem.mem[10] [7]),
    .S(_135_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand4b_1 _274_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [0]),
    .D(\fifomem.waddr [1]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor3b_1 _275_ (
    .A(_129_),
    .B(_130_),
    .C_N(_134_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__mux2_1 _276_ (
    .A0(\fifomem.mem[11] [0]),
    .A1(_136_),
    .S(_145_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _277_ (
    .A0(\fifomem.mem[11] [1]),
    .A1(_137_),
    .S(_145_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _278_ (
    .A0(\fifomem.mem[11] [2]),
    .A1(_138_),
    .S(_145_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _279_ (
    .A0(\fifomem.mem[11] [3]),
    .A1(_139_),
    .S(_145_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _280_ (
    .A0(\fifomem.mem[11] [4]),
    .A1(_140_),
    .S(_145_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _281_ (
    .A0(\fifomem.mem[11] [5]),
    .A1(_141_),
    .S(_145_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _282_ (
    .A0(\fifomem.mem[11] [6]),
    .A1(_142_),
    .S(_145_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _283_ (
    .A0(\fifomem.mem[11] [7]),
    .A1(_143_),
    .S(_145_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor4b_1 _284_ (
    .A(wfull),
    .B(\fifomem.waddr [2]),
    .C(\fifomem.waddr [3]),
    .D_N(winc),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand3_1 _285_ (
    .A(_129_),
    .B(_130_),
    .C(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__mux2_1 _286_ (
    .A0(_136_),
    .A1(\fifomem.mem[0] [0]),
    .S(_147_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _287_ (
    .A0(_137_),
    .A1(\fifomem.mem[0] [1]),
    .S(_147_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _288_ (
    .A0(_138_),
    .A1(\fifomem.mem[0] [2]),
    .S(_147_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _289_ (
    .A0(_139_),
    .A1(\fifomem.mem[0] [3]),
    .S(_147_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _290_ (
    .A0(_140_),
    .A1(\fifomem.mem[0] [4]),
    .S(_147_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _291_ (
    .A0(_141_),
    .A1(\fifomem.mem[0] [5]),
    .S(_147_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _292_ (
    .A0(_142_),
    .A1(\fifomem.mem[0] [6]),
    .S(_147_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _293_ (
    .A0(_143_),
    .A1(\fifomem.mem[0] [7]),
    .S(_147_),
    .X(_023_)
  );
  sky130_fd_sc_hd__nor4bb_1 _294_ (
    .A(wfull),
    .B(\fifomem.waddr [1]),
    .C_N(\fifomem.waddr [0]),
    .D_N(winc),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(_134_),
    .B(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__mux2_1 _296_ (
    .A0(_136_),
    .A1(\fifomem.mem[9] [0]),
    .S(_149_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _297_ (
    .A0(_137_),
    .A1(\fifomem.mem[9] [1]),
    .S(_149_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _298_ (
    .A0(_138_),
    .A1(\fifomem.mem[9] [2]),
    .S(_149_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _299_ (
    .A0(_139_),
    .A1(\fifomem.mem[9] [3]),
    .S(_149_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _300_ (
    .A0(_140_),
    .A1(\fifomem.mem[9] [4]),
    .S(_149_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _301_ (
    .A0(_141_),
    .A1(\fifomem.mem[9] [5]),
    .S(_149_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _302_ (
    .A0(_142_),
    .A1(\fifomem.mem[9] [6]),
    .S(_149_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _303_ (
    .A0(_143_),
    .A1(\fifomem.mem[9] [7]),
    .S(_149_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand3_1 _304_ (
    .A(_129_),
    .B(_130_),
    .C(_134_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__mux2_1 _305_ (
    .A0(_136_),
    .A1(\fifomem.mem[8] [0]),
    .S(_150_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _306_ (
    .A0(_137_),
    .A1(\fifomem.mem[8] [1]),
    .S(_150_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _307_ (
    .A0(_138_),
    .A1(\fifomem.mem[8] [2]),
    .S(_150_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _308_ (
    .A0(_139_),
    .A1(\fifomem.mem[8] [3]),
    .S(_150_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _309_ (
    .A0(_140_),
    .A1(\fifomem.mem[8] [4]),
    .S(_150_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _310_ (
    .A0(_141_),
    .A1(\fifomem.mem[8] [5]),
    .S(_150_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _311_ (
    .A0(_142_),
    .A1(\fifomem.mem[8] [6]),
    .S(_150_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _312_ (
    .A0(_143_),
    .A1(\fifomem.mem[8] [7]),
    .S(_150_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nor4bb_1 _313_ (
    .A(wfull),
    .B(\fifomem.waddr [3]),
    .C_N(\fifomem.waddr [2]),
    .D_N(winc),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2b_1 _314_ (
    .A(_144_),
    .B_N(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__mux2_1 _315_ (
    .A0(\fifomem.mem[7] [0]),
    .A1(_136_),
    .S(_152_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _316_ (
    .A0(\fifomem.mem[7] [1]),
    .A1(_137_),
    .S(_152_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _317_ (
    .A0(\fifomem.mem[7] [2]),
    .A1(_138_),
    .S(_152_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _318_ (
    .A0(\fifomem.mem[7] [3]),
    .A1(_139_),
    .S(_152_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _319_ (
    .A0(\fifomem.mem[7] [4]),
    .A1(_140_),
    .S(_152_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _320_ (
    .A0(\fifomem.mem[7] [5]),
    .A1(_141_),
    .S(_152_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _321_ (
    .A0(\fifomem.mem[7] [6]),
    .A1(_142_),
    .S(_152_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _322_ (
    .A0(\fifomem.mem[7] [7]),
    .A1(_143_),
    .S(_152_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _323_ (
    .A(_131_),
    .B(_151_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__mux2_1 _324_ (
    .A0(_136_),
    .A1(\fifomem.mem[6] [0]),
    .S(_153_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _325_ (
    .A0(_137_),
    .A1(\fifomem.mem[6] [1]),
    .S(_153_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _326_ (
    .A0(_138_),
    .A1(\fifomem.mem[6] [2]),
    .S(_153_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _327_ (
    .A0(_139_),
    .A1(\fifomem.mem[6] [3]),
    .S(_153_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _328_ (
    .A0(_140_),
    .A1(\fifomem.mem[6] [4]),
    .S(_153_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _329_ (
    .A0(_141_),
    .A1(\fifomem.mem[6] [5]),
    .S(_153_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _330_ (
    .A0(_142_),
    .A1(\fifomem.mem[6] [6]),
    .S(_153_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _331_ (
    .A0(_143_),
    .A1(\fifomem.mem[6] [7]),
    .S(_153_),
    .X(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _332_ (
    .A(_148_),
    .B(_151_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__mux2_1 _333_ (
    .A0(_136_),
    .A1(\fifomem.mem[5] [0]),
    .S(_154_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _334_ (
    .A0(_137_),
    .A1(\fifomem.mem[5] [1]),
    .S(_154_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _335_ (
    .A0(_138_),
    .A1(\fifomem.mem[5] [2]),
    .S(_154_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _336_ (
    .A0(_139_),
    .A1(\fifomem.mem[5] [3]),
    .S(_154_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _337_ (
    .A0(_140_),
    .A1(\fifomem.mem[5] [4]),
    .S(_154_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _338_ (
    .A0(_141_),
    .A1(\fifomem.mem[5] [5]),
    .S(_154_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _339_ (
    .A0(_142_),
    .A1(\fifomem.mem[5] [6]),
    .S(_154_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _340_ (
    .A0(_143_),
    .A1(\fifomem.mem[5] [7]),
    .S(_154_),
    .X(_063_)
  );
  sky130_fd_sc_hd__nand3_1 _341_ (
    .A(_129_),
    .B(_130_),
    .C(_151_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__mux2_1 _342_ (
    .A0(_136_),
    .A1(\fifomem.mem[4] [0]),
    .S(_155_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _343_ (
    .A0(_137_),
    .A1(\fifomem.mem[4] [1]),
    .S(_155_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _344_ (
    .A0(_138_),
    .A1(\fifomem.mem[4] [2]),
    .S(_155_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _345_ (
    .A0(_139_),
    .A1(\fifomem.mem[4] [3]),
    .S(_155_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _346_ (
    .A0(_140_),
    .A1(\fifomem.mem[4] [4]),
    .S(_155_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _347_ (
    .A0(_141_),
    .A1(\fifomem.mem[4] [5]),
    .S(_155_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _348_ (
    .A0(_142_),
    .A1(\fifomem.mem[4] [6]),
    .S(_155_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _349_ (
    .A0(_143_),
    .A1(\fifomem.mem[4] [7]),
    .S(_155_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand3b_1 _350_ (
    .A_N(_144_),
    .B(_133_),
    .C(_132_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__mux2_1 _351_ (
    .A0(_136_),
    .A1(\fifomem.mem[3] [0]),
    .S(_156_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_1 _352_ (
    .A0(_137_),
    .A1(\fifomem.mem[3] [1]),
    .S(_156_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _353_ (
    .A0(_138_),
    .A1(\fifomem.mem[3] [2]),
    .S(_156_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _354_ (
    .A0(_139_),
    .A1(\fifomem.mem[3] [3]),
    .S(_156_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _355_ (
    .A0(_140_),
    .A1(\fifomem.mem[3] [4]),
    .S(_156_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _356_ (
    .A0(_141_),
    .A1(\fifomem.mem[3] [5]),
    .S(_156_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_1 _357_ (
    .A0(_142_),
    .A1(\fifomem.mem[3] [6]),
    .S(_156_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _358_ (
    .A0(_143_),
    .A1(\fifomem.mem[3] [7]),
    .S(_156_),
    .X(_079_)
  );
  sky130_fd_sc_hd__nand3_1 _359_ (
    .A(_131_),
    .B(_132_),
    .C(_133_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__mux2_1 _360_ (
    .A0(_136_),
    .A1(\fifomem.mem[2] [0]),
    .S(_157_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _361_ (
    .A0(_137_),
    .A1(\fifomem.mem[2] [1]),
    .S(_157_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_1 _362_ (
    .A0(_138_),
    .A1(\fifomem.mem[2] [2]),
    .S(_157_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _363_ (
    .A0(_139_),
    .A1(\fifomem.mem[2] [3]),
    .S(_157_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _364_ (
    .A0(_140_),
    .A1(\fifomem.mem[2] [4]),
    .S(_157_),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _365_ (
    .A0(_141_),
    .A1(\fifomem.mem[2] [5]),
    .S(_157_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _366_ (
    .A0(_142_),
    .A1(\fifomem.mem[2] [6]),
    .S(_157_),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _367_ (
    .A0(_143_),
    .A1(\fifomem.mem[2] [7]),
    .S(_157_),
    .X(_087_)
  );
  sky130_fd_sc_hd__nand3_1 _368_ (
    .A(_132_),
    .B(_133_),
    .C(_148_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__mux2_1 _369_ (
    .A0(_136_),
    .A1(\fifomem.mem[1] [0]),
    .S(_158_),
    .X(_088_)
  );
  sky130_fd_sc_hd__mux2_1 _370_ (
    .A0(_137_),
    .A1(\fifomem.mem[1] [1]),
    .S(_158_),
    .X(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _371_ (
    .A0(_138_),
    .A1(\fifomem.mem[1] [2]),
    .S(_158_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _372_ (
    .A0(_139_),
    .A1(\fifomem.mem[1] [3]),
    .S(_158_),
    .X(_091_)
  );
  sky130_fd_sc_hd__mux2_1 _373_ (
    .A0(_140_),
    .A1(\fifomem.mem[1] [4]),
    .S(_158_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_1 _374_ (
    .A0(_141_),
    .A1(\fifomem.mem[1] [5]),
    .S(_158_),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_1 _375_ (
    .A0(_142_),
    .A1(\fifomem.mem[1] [6]),
    .S(_158_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_1 _376_ (
    .A0(_143_),
    .A1(\fifomem.mem[1] [7]),
    .S(_158_),
    .X(_095_)
  );
  sky130_fd_sc_hd__nand4b_1 _377_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [2]),
    .D(\fifomem.waddr [3]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _378_ (
    .A(_144_),
    .B(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__mux2_1 _379_ (
    .A0(\fifomem.mem[15] [0]),
    .A1(_136_),
    .S(_160_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_1 _380_ (
    .A0(\fifomem.mem[15] [1]),
    .A1(_137_),
    .S(_160_),
    .X(_097_)
  );
  sky130_fd_sc_hd__mux2_1 _381_ (
    .A0(\fifomem.mem[15] [2]),
    .A1(_138_),
    .S(_160_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _382_ (
    .A0(\fifomem.mem[15] [3]),
    .A1(_139_),
    .S(_160_),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _383_ (
    .A0(\fifomem.mem[15] [4]),
    .A1(_140_),
    .S(_160_),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_1 _384_ (
    .A0(\fifomem.mem[15] [5]),
    .A1(_141_),
    .S(_160_),
    .X(_101_)
  );
  sky130_fd_sc_hd__mux2_1 _385_ (
    .A0(\fifomem.mem[15] [6]),
    .A1(_142_),
    .S(_160_),
    .X(_102_)
  );
  sky130_fd_sc_hd__mux2_1 _386_ (
    .A0(\fifomem.mem[15] [7]),
    .A1(_143_),
    .S(_160_),
    .X(_103_)
  );
  sky130_fd_sc_hd__nor3b_1 _387_ (
    .A(_130_),
    .B(_159_),
    .C_N(_129_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__mux2_1 _388_ (
    .A0(\fifomem.mem[14] [0]),
    .A1(_136_),
    .S(_161_),
    .X(_104_)
  );
  sky130_fd_sc_hd__mux2_1 _389_ (
    .A0(\fifomem.mem[14] [1]),
    .A1(_137_),
    .S(_161_),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_1 _390_ (
    .A0(\fifomem.mem[14] [2]),
    .A1(_138_),
    .S(_161_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_1 _391_ (
    .A0(\fifomem.mem[14] [3]),
    .A1(_139_),
    .S(_161_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _392_ (
    .A0(\fifomem.mem[14] [4]),
    .A1(_140_),
    .S(_161_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_1 _393_ (
    .A0(\fifomem.mem[14] [5]),
    .A1(_141_),
    .S(_161_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _394_ (
    .A0(\fifomem.mem[14] [6]),
    .A1(_142_),
    .S(_161_),
    .X(_110_)
  );
  sky130_fd_sc_hd__mux2_1 _395_ (
    .A0(\fifomem.mem[14] [7]),
    .A1(_143_),
    .S(_161_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nor3b_1 _396_ (
    .A(_132_),
    .B(_133_),
    .C_N(_148_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__mux2_1 _397_ (
    .A0(\fifomem.mem[13] [0]),
    .A1(_136_),
    .S(_162_),
    .X(_112_)
  );
  sky130_fd_sc_hd__mux2_1 _398_ (
    .A0(\fifomem.mem[13] [1]),
    .A1(_137_),
    .S(_162_),
    .X(_113_)
  );
  sky130_fd_sc_hd__mux2_1 _399_ (
    .A0(\fifomem.mem[13] [2]),
    .A1(_138_),
    .S(_162_),
    .X(_114_)
  );
  sky130_fd_sc_hd__mux2_1 _400_ (
    .A0(\fifomem.mem[13] [3]),
    .A1(_139_),
    .S(_162_),
    .X(_115_)
  );
  sky130_fd_sc_hd__mux2_1 _401_ (
    .A0(\fifomem.mem[13] [4]),
    .A1(_140_),
    .S(_162_),
    .X(_116_)
  );
  sky130_fd_sc_hd__mux2_1 _402_ (
    .A0(\fifomem.mem[13] [5]),
    .A1(_141_),
    .S(_162_),
    .X(_117_)
  );
  sky130_fd_sc_hd__mux2_1 _403_ (
    .A0(\fifomem.mem[13] [6]),
    .A1(_142_),
    .S(_162_),
    .X(_118_)
  );
  sky130_fd_sc_hd__mux2_1 _404_ (
    .A0(\fifomem.mem[13] [7]),
    .A1(_143_),
    .S(_162_),
    .X(_119_)
  );
  sky130_fd_sc_hd__nand3b_1 _405_ (
    .A_N(_159_),
    .B(_130_),
    .C(_129_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__mux2_1 _406_ (
    .A0(_136_),
    .A1(\fifomem.mem[12] [0]),
    .S(_163_),
    .X(_120_)
  );
  sky130_fd_sc_hd__mux2_1 _407_ (
    .A0(_137_),
    .A1(\fifomem.mem[12] [1]),
    .S(_163_),
    .X(_121_)
  );
  sky130_fd_sc_hd__mux2_1 _408_ (
    .A0(_138_),
    .A1(\fifomem.mem[12] [2]),
    .S(_163_),
    .X(_122_)
  );
  sky130_fd_sc_hd__mux2_1 _409_ (
    .A0(_139_),
    .A1(\fifomem.mem[12] [3]),
    .S(_163_),
    .X(_123_)
  );
  sky130_fd_sc_hd__mux2_1 _410_ (
    .A0(_140_),
    .A1(\fifomem.mem[12] [4]),
    .S(_163_),
    .X(_124_)
  );
  sky130_fd_sc_hd__mux2_1 _411_ (
    .A0(_141_),
    .A1(\fifomem.mem[12] [5]),
    .S(_163_),
    .X(_125_)
  );
  sky130_fd_sc_hd__mux2_1 _412_ (
    .A0(_142_),
    .A1(\fifomem.mem[12] [6]),
    .S(_163_),
    .X(_126_)
  );
  sky130_fd_sc_hd__mux2_1 _413_ (
    .A0(_143_),
    .A1(\fifomem.mem[12] [7]),
    .S(_163_),
    .X(_127_)
  );
  sky130_fd_sc_hd__mux4_2 _414_ (
    .A0(\fifomem.mem[12] [0]),
    .A1(\fifomem.mem[13] [0]),
    .A2(\fifomem.mem[14] [0]),
    .A3(\fifomem.mem[15] [0]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_164_)
  );
  sky130_fd_sc_hd__mux4_2 _415_ (
    .A0(\fifomem.mem[8] [0]),
    .A1(\fifomem.mem[9] [0]),
    .A2(\fifomem.mem[10] [0]),
    .A3(\fifomem.mem[11] [0]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_165_)
  );
  sky130_fd_sc_hd__mux4_2 _416_ (
    .A0(\fifomem.mem[4] [0]),
    .A1(\fifomem.mem[5] [0]),
    .A2(\fifomem.mem[6] [0]),
    .A3(\fifomem.mem[7] [0]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_166_)
  );
  sky130_fd_sc_hd__mux4_2 _417_ (
    .A0(\fifomem.mem[0] [0]),
    .A1(\fifomem.mem[2] [0]),
    .A2(\fifomem.mem[1] [0]),
    .A3(\fifomem.mem[3] [0]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(_167_)
  );
  sky130_fd_sc_hd__mux4_2 _418_ (
    .A0(_167_),
    .A1(_166_),
    .A2(_165_),
    .A3(_164_),
    .S0(\fifomem.raddr [2]),
    .S1(\fifomem.raddr [3]),
    .X(rdata[0])
  );
  sky130_fd_sc_hd__mux4_2 _419_ (
    .A0(\fifomem.mem[12] [1]),
    .A1(\fifomem.mem[13] [1]),
    .A2(\fifomem.mem[14] [1]),
    .A3(\fifomem.mem[15] [1]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_168_)
  );
  sky130_fd_sc_hd__mux4_2 _420_ (
    .A0(\fifomem.mem[8] [1]),
    .A1(\fifomem.mem[9] [1]),
    .A2(\fifomem.mem[10] [1]),
    .A3(\fifomem.mem[11] [1]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_169_)
  );
  sky130_fd_sc_hd__mux4_2 _421_ (
    .A0(\fifomem.mem[4] [1]),
    .A1(\fifomem.mem[5] [1]),
    .A2(\fifomem.mem[6] [1]),
    .A3(\fifomem.mem[7] [1]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_170_)
  );
  sky130_fd_sc_hd__mux4_2 _422_ (
    .A0(\fifomem.mem[0] [1]),
    .A1(\fifomem.mem[2] [1]),
    .A2(\fifomem.mem[1] [1]),
    .A3(\fifomem.mem[3] [1]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(_171_)
  );
  sky130_fd_sc_hd__mux4_2 _423_ (
    .A0(_171_),
    .A1(_170_),
    .A2(_169_),
    .A3(_168_),
    .S0(\fifomem.raddr [2]),
    .S1(\fifomem.raddr [3]),
    .X(rdata[1])
  );
  sky130_fd_sc_hd__mux4_2 _424_ (
    .A0(\fifomem.mem[12] [2]),
    .A1(\fifomem.mem[13] [2]),
    .A2(\fifomem.mem[14] [2]),
    .A3(\fifomem.mem[15] [2]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_172_)
  );
  sky130_fd_sc_hd__mux4_2 _425_ (
    .A0(\fifomem.mem[8] [2]),
    .A1(\fifomem.mem[9] [2]),
    .A2(\fifomem.mem[10] [2]),
    .A3(\fifomem.mem[11] [2]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_173_)
  );
  sky130_fd_sc_hd__mux4_2 _426_ (
    .A0(\fifomem.mem[4] [2]),
    .A1(\fifomem.mem[5] [2]),
    .A2(\fifomem.mem[6] [2]),
    .A3(\fifomem.mem[7] [2]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_174_)
  );
  sky130_fd_sc_hd__mux4_2 _427_ (
    .A0(\fifomem.mem[0] [2]),
    .A1(\fifomem.mem[2] [2]),
    .A2(\fifomem.mem[1] [2]),
    .A3(\fifomem.mem[3] [2]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(_175_)
  );
  sky130_fd_sc_hd__mux4_2 _428_ (
    .A0(_175_),
    .A1(_174_),
    .A2(_173_),
    .A3(_172_),
    .S0(\fifomem.raddr [2]),
    .S1(\fifomem.raddr [3]),
    .X(rdata[2])
  );
  sky130_fd_sc_hd__mux4_2 _429_ (
    .A0(\fifomem.mem[12] [3]),
    .A1(\fifomem.mem[13] [3]),
    .A2(\fifomem.mem[14] [3]),
    .A3(\fifomem.mem[15] [3]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_176_)
  );
  sky130_fd_sc_hd__mux4_2 _430_ (
    .A0(\fifomem.mem[8] [3]),
    .A1(\fifomem.mem[9] [3]),
    .A2(\fifomem.mem[10] [3]),
    .A3(\fifomem.mem[11] [3]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_177_)
  );
  sky130_fd_sc_hd__mux4_2 _431_ (
    .A0(\fifomem.mem[4] [3]),
    .A1(\fifomem.mem[5] [3]),
    .A2(\fifomem.mem[6] [3]),
    .A3(\fifomem.mem[7] [3]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_178_)
  );
  sky130_fd_sc_hd__mux4_2 _432_ (
    .A0(\fifomem.mem[0] [3]),
    .A1(\fifomem.mem[2] [3]),
    .A2(\fifomem.mem[1] [3]),
    .A3(\fifomem.mem[3] [3]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(_179_)
  );
  sky130_fd_sc_hd__mux4_2 _433_ (
    .A0(_179_),
    .A1(_178_),
    .A2(_177_),
    .A3(_176_),
    .S0(\fifomem.raddr [2]),
    .S1(\fifomem.raddr [3]),
    .X(rdata[3])
  );
  sky130_fd_sc_hd__mux4_2 _434_ (
    .A0(\fifomem.mem[12] [4]),
    .A1(\fifomem.mem[13] [4]),
    .A2(\fifomem.mem[14] [4]),
    .A3(\fifomem.mem[15] [4]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_180_)
  );
  sky130_fd_sc_hd__mux4_2 _435_ (
    .A0(\fifomem.mem[8] [4]),
    .A1(\fifomem.mem[9] [4]),
    .A2(\fifomem.mem[10] [4]),
    .A3(\fifomem.mem[11] [4]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_181_)
  );
  sky130_fd_sc_hd__mux4_2 _436_ (
    .A0(\fifomem.mem[4] [4]),
    .A1(\fifomem.mem[5] [4]),
    .A2(\fifomem.mem[6] [4]),
    .A3(\fifomem.mem[7] [4]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_182_)
  );
  sky130_fd_sc_hd__mux4_2 _437_ (
    .A0(\fifomem.mem[0] [4]),
    .A1(\fifomem.mem[2] [4]),
    .A2(\fifomem.mem[1] [4]),
    .A3(\fifomem.mem[3] [4]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(_183_)
  );
  sky130_fd_sc_hd__mux4_2 _438_ (
    .A0(_183_),
    .A1(_182_),
    .A2(_181_),
    .A3(_180_),
    .S0(\fifomem.raddr [2]),
    .S1(\fifomem.raddr [3]),
    .X(rdata[4])
  );
  sky130_fd_sc_hd__mux4_2 _439_ (
    .A0(\fifomem.mem[12] [5]),
    .A1(\fifomem.mem[13] [5]),
    .A2(\fifomem.mem[14] [5]),
    .A3(\fifomem.mem[15] [5]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_184_)
  );
  sky130_fd_sc_hd__mux4_2 _440_ (
    .A0(\fifomem.mem[8] [5]),
    .A1(\fifomem.mem[9] [5]),
    .A2(\fifomem.mem[10] [5]),
    .A3(\fifomem.mem[11] [5]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_185_)
  );
  sky130_fd_sc_hd__mux4_2 _441_ (
    .A0(\fifomem.mem[4] [5]),
    .A1(\fifomem.mem[5] [5]),
    .A2(\fifomem.mem[6] [5]),
    .A3(\fifomem.mem[7] [5]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_186_)
  );
  sky130_fd_sc_hd__mux4_2 _442_ (
    .A0(\fifomem.mem[0] [5]),
    .A1(\fifomem.mem[2] [5]),
    .A2(\fifomem.mem[1] [5]),
    .A3(\fifomem.mem[3] [5]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(_187_)
  );
  sky130_fd_sc_hd__mux4_2 _443_ (
    .A0(_187_),
    .A1(_186_),
    .A2(_185_),
    .A3(_184_),
    .S0(\fifomem.raddr [2]),
    .S1(\fifomem.raddr [3]),
    .X(rdata[5])
  );
  sky130_fd_sc_hd__mux4_2 _444_ (
    .A0(\fifomem.mem[12] [6]),
    .A1(\fifomem.mem[13] [6]),
    .A2(\fifomem.mem[14] [6]),
    .A3(\fifomem.mem[15] [6]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_188_)
  );
  sky130_fd_sc_hd__mux4_2 _445_ (
    .A0(\fifomem.mem[8] [6]),
    .A1(\fifomem.mem[9] [6]),
    .A2(\fifomem.mem[10] [6]),
    .A3(\fifomem.mem[11] [6]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_189_)
  );
  sky130_fd_sc_hd__mux4_2 _446_ (
    .A0(\fifomem.mem[4] [6]),
    .A1(\fifomem.mem[5] [6]),
    .A2(\fifomem.mem[6] [6]),
    .A3(\fifomem.mem[7] [6]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_190_)
  );
  sky130_fd_sc_hd__mux4_2 _447_ (
    .A0(\fifomem.mem[0] [6]),
    .A1(\fifomem.mem[2] [6]),
    .A2(\fifomem.mem[1] [6]),
    .A3(\fifomem.mem[3] [6]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(_191_)
  );
  sky130_fd_sc_hd__mux4_2 _448_ (
    .A0(_191_),
    .A1(_190_),
    .A2(_189_),
    .A3(_188_),
    .S0(\fifomem.raddr [2]),
    .S1(\fifomem.raddr [3]),
    .X(rdata[6])
  );
  sky130_fd_sc_hd__mux4_2 _449_ (
    .A0(\fifomem.mem[12] [7]),
    .A1(\fifomem.mem[13] [7]),
    .A2(\fifomem.mem[14] [7]),
    .A3(\fifomem.mem[15] [7]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_192_)
  );
  sky130_fd_sc_hd__mux4_2 _450_ (
    .A0(\fifomem.mem[8] [7]),
    .A1(\fifomem.mem[9] [7]),
    .A2(\fifomem.mem[10] [7]),
    .A3(\fifomem.mem[11] [7]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_193_)
  );
  sky130_fd_sc_hd__mux4_2 _451_ (
    .A0(\fifomem.mem[4] [7]),
    .A1(\fifomem.mem[5] [7]),
    .A2(\fifomem.mem[6] [7]),
    .A3(\fifomem.mem[7] [7]),
    .S0(\fifomem.raddr [0]),
    .S1(\fifomem.raddr [1]),
    .X(_194_)
  );
  sky130_fd_sc_hd__mux4_2 _452_ (
    .A0(\fifomem.mem[0] [7]),
    .A1(\fifomem.mem[2] [7]),
    .A2(\fifomem.mem[1] [7]),
    .A3(\fifomem.mem[3] [7]),
    .S0(\fifomem.raddr [1]),
    .S1(\fifomem.raddr [0]),
    .X(_195_)
  );
  sky130_fd_sc_hd__mux4_2 _453_ (
    .A0(_195_),
    .A1(_194_),
    .A2(_193_),
    .A3(_192_),
    .S0(\fifomem.raddr [2]),
    .S1(\fifomem.raddr [3]),
    .X(rdata[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _454_ (
    .CLK(wclk),
    .D(_000_),
    .Q(\fifomem.mem[10] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _455_ (
    .CLK(wclk),
    .D(_001_),
    .Q(\fifomem.mem[10] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _456_ (
    .CLK(wclk),
    .D(_002_),
    .Q(\fifomem.mem[10] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _457_ (
    .CLK(wclk),
    .D(_003_),
    .Q(\fifomem.mem[10] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _458_ (
    .CLK(wclk),
    .D(_004_),
    .Q(\fifomem.mem[10] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _459_ (
    .CLK(wclk),
    .D(_005_),
    .Q(\fifomem.mem[10] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _460_ (
    .CLK(wclk),
    .D(_006_),
    .Q(\fifomem.mem[10] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _461_ (
    .CLK(wclk),
    .D(_007_),
    .Q(\fifomem.mem[10] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _462_ (
    .CLK(wclk),
    .D(_008_),
    .Q(\fifomem.mem[11] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _463_ (
    .CLK(wclk),
    .D(_009_),
    .Q(\fifomem.mem[11] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _464_ (
    .CLK(wclk),
    .D(_010_),
    .Q(\fifomem.mem[11] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _465_ (
    .CLK(wclk),
    .D(_011_),
    .Q(\fifomem.mem[11] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _466_ (
    .CLK(wclk),
    .D(_012_),
    .Q(\fifomem.mem[11] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _467_ (
    .CLK(wclk),
    .D(_013_),
    .Q(\fifomem.mem[11] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _468_ (
    .CLK(wclk),
    .D(_014_),
    .Q(\fifomem.mem[11] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _469_ (
    .CLK(wclk),
    .D(_015_),
    .Q(\fifomem.mem[11] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _470_ (
    .CLK(wclk),
    .D(_016_),
    .Q(\fifomem.mem[0] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _471_ (
    .CLK(wclk),
    .D(_017_),
    .Q(\fifomem.mem[0] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _472_ (
    .CLK(wclk),
    .D(_018_),
    .Q(\fifomem.mem[0] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _473_ (
    .CLK(wclk),
    .D(_019_),
    .Q(\fifomem.mem[0] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _474_ (
    .CLK(wclk),
    .D(_020_),
    .Q(\fifomem.mem[0] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _475_ (
    .CLK(wclk),
    .D(_021_),
    .Q(\fifomem.mem[0] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _476_ (
    .CLK(wclk),
    .D(_022_),
    .Q(\fifomem.mem[0] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _477_ (
    .CLK(wclk),
    .D(_023_),
    .Q(\fifomem.mem[0] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _478_ (
    .CLK(wclk),
    .D(_024_),
    .Q(\fifomem.mem[9] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _479_ (
    .CLK(wclk),
    .D(_025_),
    .Q(\fifomem.mem[9] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _480_ (
    .CLK(wclk),
    .D(_026_),
    .Q(\fifomem.mem[9] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _481_ (
    .CLK(wclk),
    .D(_027_),
    .Q(\fifomem.mem[9] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _482_ (
    .CLK(wclk),
    .D(_028_),
    .Q(\fifomem.mem[9] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _483_ (
    .CLK(wclk),
    .D(_029_),
    .Q(\fifomem.mem[9] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _484_ (
    .CLK(wclk),
    .D(_030_),
    .Q(\fifomem.mem[9] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _485_ (
    .CLK(wclk),
    .D(_031_),
    .Q(\fifomem.mem[9] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _486_ (
    .CLK(wclk),
    .D(_032_),
    .Q(\fifomem.mem[8] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _487_ (
    .CLK(wclk),
    .D(_033_),
    .Q(\fifomem.mem[8] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _488_ (
    .CLK(wclk),
    .D(_034_),
    .Q(\fifomem.mem[8] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _489_ (
    .CLK(wclk),
    .D(_035_),
    .Q(\fifomem.mem[8] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _490_ (
    .CLK(wclk),
    .D(_036_),
    .Q(\fifomem.mem[8] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _491_ (
    .CLK(wclk),
    .D(_037_),
    .Q(\fifomem.mem[8] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _492_ (
    .CLK(wclk),
    .D(_038_),
    .Q(\fifomem.mem[8] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _493_ (
    .CLK(wclk),
    .D(_039_),
    .Q(\fifomem.mem[8] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _494_ (
    .CLK(wclk),
    .D(_040_),
    .Q(\fifomem.mem[7] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _495_ (
    .CLK(wclk),
    .D(_041_),
    .Q(\fifomem.mem[7] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _496_ (
    .CLK(wclk),
    .D(_042_),
    .Q(\fifomem.mem[7] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _497_ (
    .CLK(wclk),
    .D(_043_),
    .Q(\fifomem.mem[7] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _498_ (
    .CLK(wclk),
    .D(_044_),
    .Q(\fifomem.mem[7] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _499_ (
    .CLK(wclk),
    .D(_045_),
    .Q(\fifomem.mem[7] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _500_ (
    .CLK(wclk),
    .D(_046_),
    .Q(\fifomem.mem[7] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _501_ (
    .CLK(wclk),
    .D(_047_),
    .Q(\fifomem.mem[7] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _502_ (
    .CLK(wclk),
    .D(_048_),
    .Q(\fifomem.mem[6] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _503_ (
    .CLK(wclk),
    .D(_049_),
    .Q(\fifomem.mem[6] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _504_ (
    .CLK(wclk),
    .D(_050_),
    .Q(\fifomem.mem[6] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _505_ (
    .CLK(wclk),
    .D(_051_),
    .Q(\fifomem.mem[6] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _506_ (
    .CLK(wclk),
    .D(_052_),
    .Q(\fifomem.mem[6] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _507_ (
    .CLK(wclk),
    .D(_053_),
    .Q(\fifomem.mem[6] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _508_ (
    .CLK(wclk),
    .D(_054_),
    .Q(\fifomem.mem[6] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _509_ (
    .CLK(wclk),
    .D(_055_),
    .Q(\fifomem.mem[6] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _510_ (
    .CLK(wclk),
    .D(_056_),
    .Q(\fifomem.mem[5] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _511_ (
    .CLK(wclk),
    .D(_057_),
    .Q(\fifomem.mem[5] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _512_ (
    .CLK(wclk),
    .D(_058_),
    .Q(\fifomem.mem[5] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _513_ (
    .CLK(wclk),
    .D(_059_),
    .Q(\fifomem.mem[5] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _514_ (
    .CLK(wclk),
    .D(_060_),
    .Q(\fifomem.mem[5] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _515_ (
    .CLK(wclk),
    .D(_061_),
    .Q(\fifomem.mem[5] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _516_ (
    .CLK(wclk),
    .D(_062_),
    .Q(\fifomem.mem[5] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _517_ (
    .CLK(wclk),
    .D(_063_),
    .Q(\fifomem.mem[5] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _518_ (
    .CLK(wclk),
    .D(_064_),
    .Q(\fifomem.mem[4] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _519_ (
    .CLK(wclk),
    .D(_065_),
    .Q(\fifomem.mem[4] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _520_ (
    .CLK(wclk),
    .D(_066_),
    .Q(\fifomem.mem[4] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _521_ (
    .CLK(wclk),
    .D(_067_),
    .Q(\fifomem.mem[4] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _522_ (
    .CLK(wclk),
    .D(_068_),
    .Q(\fifomem.mem[4] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _523_ (
    .CLK(wclk),
    .D(_069_),
    .Q(\fifomem.mem[4] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _524_ (
    .CLK(wclk),
    .D(_070_),
    .Q(\fifomem.mem[4] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _525_ (
    .CLK(wclk),
    .D(_071_),
    .Q(\fifomem.mem[4] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _526_ (
    .CLK(wclk),
    .D(_072_),
    .Q(\fifomem.mem[3] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _527_ (
    .CLK(wclk),
    .D(_073_),
    .Q(\fifomem.mem[3] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _528_ (
    .CLK(wclk),
    .D(_074_),
    .Q(\fifomem.mem[3] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _529_ (
    .CLK(wclk),
    .D(_075_),
    .Q(\fifomem.mem[3] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _530_ (
    .CLK(wclk),
    .D(_076_),
    .Q(\fifomem.mem[3] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _531_ (
    .CLK(wclk),
    .D(_077_),
    .Q(\fifomem.mem[3] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _532_ (
    .CLK(wclk),
    .D(_078_),
    .Q(\fifomem.mem[3] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _533_ (
    .CLK(wclk),
    .D(_079_),
    .Q(\fifomem.mem[3] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _534_ (
    .CLK(wclk),
    .D(_080_),
    .Q(\fifomem.mem[2] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _535_ (
    .CLK(wclk),
    .D(_081_),
    .Q(\fifomem.mem[2] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _536_ (
    .CLK(wclk),
    .D(_082_),
    .Q(\fifomem.mem[2] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _537_ (
    .CLK(wclk),
    .D(_083_),
    .Q(\fifomem.mem[2] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _538_ (
    .CLK(wclk),
    .D(_084_),
    .Q(\fifomem.mem[2] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _539_ (
    .CLK(wclk),
    .D(_085_),
    .Q(\fifomem.mem[2] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _540_ (
    .CLK(wclk),
    .D(_086_),
    .Q(\fifomem.mem[2] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _541_ (
    .CLK(wclk),
    .D(_087_),
    .Q(\fifomem.mem[2] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _542_ (
    .CLK(wclk),
    .D(_088_),
    .Q(\fifomem.mem[1] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _543_ (
    .CLK(wclk),
    .D(_089_),
    .Q(\fifomem.mem[1] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _544_ (
    .CLK(wclk),
    .D(_090_),
    .Q(\fifomem.mem[1] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _545_ (
    .CLK(wclk),
    .D(_091_),
    .Q(\fifomem.mem[1] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _546_ (
    .CLK(wclk),
    .D(_092_),
    .Q(\fifomem.mem[1] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _547_ (
    .CLK(wclk),
    .D(_093_),
    .Q(\fifomem.mem[1] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _548_ (
    .CLK(wclk),
    .D(_094_),
    .Q(\fifomem.mem[1] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _549_ (
    .CLK(wclk),
    .D(_095_),
    .Q(\fifomem.mem[1] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _550_ (
    .CLK(wclk),
    .D(_096_),
    .Q(\fifomem.mem[15] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _551_ (
    .CLK(wclk),
    .D(_097_),
    .Q(\fifomem.mem[15] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _552_ (
    .CLK(wclk),
    .D(_098_),
    .Q(\fifomem.mem[15] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _553_ (
    .CLK(wclk),
    .D(_099_),
    .Q(\fifomem.mem[15] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _554_ (
    .CLK(wclk),
    .D(_100_),
    .Q(\fifomem.mem[15] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _555_ (
    .CLK(wclk),
    .D(_101_),
    .Q(\fifomem.mem[15] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _556_ (
    .CLK(wclk),
    .D(_102_),
    .Q(\fifomem.mem[15] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _557_ (
    .CLK(wclk),
    .D(_103_),
    .Q(\fifomem.mem[15] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _558_ (
    .CLK(wclk),
    .D(_104_),
    .Q(\fifomem.mem[14] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _559_ (
    .CLK(wclk),
    .D(_105_),
    .Q(\fifomem.mem[14] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _560_ (
    .CLK(wclk),
    .D(_106_),
    .Q(\fifomem.mem[14] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _561_ (
    .CLK(wclk),
    .D(_107_),
    .Q(\fifomem.mem[14] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _562_ (
    .CLK(wclk),
    .D(_108_),
    .Q(\fifomem.mem[14] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _563_ (
    .CLK(wclk),
    .D(_109_),
    .Q(\fifomem.mem[14] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _564_ (
    .CLK(wclk),
    .D(_110_),
    .Q(\fifomem.mem[14] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _565_ (
    .CLK(wclk),
    .D(_111_),
    .Q(\fifomem.mem[14] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _566_ (
    .CLK(wclk),
    .D(_112_),
    .Q(\fifomem.mem[13] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _567_ (
    .CLK(wclk),
    .D(_113_),
    .Q(\fifomem.mem[13] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _568_ (
    .CLK(wclk),
    .D(_114_),
    .Q(\fifomem.mem[13] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _569_ (
    .CLK(wclk),
    .D(_115_),
    .Q(\fifomem.mem[13] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _570_ (
    .CLK(wclk),
    .D(_116_),
    .Q(\fifomem.mem[13] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _571_ (
    .CLK(wclk),
    .D(_117_),
    .Q(\fifomem.mem[13] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _572_ (
    .CLK(wclk),
    .D(_118_),
    .Q(\fifomem.mem[13] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _573_ (
    .CLK(wclk),
    .D(_119_),
    .Q(\fifomem.mem[13] [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _574_ (
    .CLK(wclk),
    .D(_120_),
    .Q(\fifomem.mem[12] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _575_ (
    .CLK(wclk),
    .D(_121_),
    .Q(\fifomem.mem[12] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _576_ (
    .CLK(wclk),
    .D(_122_),
    .Q(\fifomem.mem[12] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _577_ (
    .CLK(wclk),
    .D(_123_),
    .Q(\fifomem.mem[12] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _578_ (
    .CLK(wclk),
    .D(_124_),
    .Q(\fifomem.mem[12] [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _579_ (
    .CLK(wclk),
    .D(_125_),
    .Q(\fifomem.mem[12] [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _580_ (
    .CLK(wclk),
    .D(_126_),
    .Q(\fifomem.mem[12] [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _581_ (
    .CLK(wclk),
    .D(_127_),
    .Q(\fifomem.mem[12] [7])
  );
  sky130_fd_sc_hd__nand2b_1 _582_ (
    .A_N(rempty),
    .B(rinc),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nand3b_1 _583_ (
    .A_N(rempty),
    .B(rinc),
    .C(\fifomem.raddr [0]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__and4b_1 _584_ (
    .A_N(rempty),
    .B(rinc),
    .C(\fifomem.raddr [0]),
    .D(\fifomem.raddr [1]),
    .X(_198_)
  );
  sky130_fd_sc_hd__nand3_1 _585_ (
    .A(\fifomem.raddr [2]),
    .B(\fifomem.raddr [3]),
    .C(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__xor2_1 _586_ (
    .A(\rptr_empty.rbin [4]),
    .B(_199_),
    .X(_200_)
  );
  sky130_fd_sc_hd__clkinv_1 _587_ (
    .A(_200_),
    .Y(\rptr_empty.rbinnext [4])
  );
  sky130_fd_sc_hd__a21o_1 _588_ (
    .A1(\fifomem.raddr [2]),
    .A2(_198_),
    .B1(\fifomem.raddr [3]),
    .X(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _589_ (
    .A(_199_),
    .B(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__clkinv_1 _590_ (
    .A(_202_),
    .Y(\rptr_empty.rbinnext [3])
  );
  sky130_fd_sc_hd__xor2_1 _591_ (
    .A(_200_),
    .B(_202_),
    .X(\rptr_empty.rgraynext [3])
  );
  sky130_fd_sc_hd__xor2_1 _592_ (
    .A(\rptr_empty.rq2_wptr [3]),
    .B(\rptr_empty.rgraynext [3]),
    .X(_203_)
  );
  sky130_fd_sc_hd__xnor2_1 _593_ (
    .A(\fifomem.raddr [2]),
    .B(_198_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__clkinv_1 _594_ (
    .A(_204_),
    .Y(\rptr_empty.rbinnext [2])
  );
  sky130_fd_sc_hd__xnor2_1 _595_ (
    .A(_202_),
    .B(\rptr_empty.rbinnext [2]),
    .Y(\rptr_empty.rgraynext [2])
  );
  sky130_fd_sc_hd__xnor2_1 _596_ (
    .A(\rptr_empty.rq2_wptr [2]),
    .B(\rptr_empty.rgraynext [2]),
    .Y(_205_)
  );
  sky130_fd_sc_hd__xnor2_1 _597_ (
    .A(\rptr_empty.rq2_wptr [4]),
    .B(_200_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__xnor2_1 _598_ (
    .A(\fifomem.raddr [1]),
    .B(_197_),
    .Y(\rptr_empty.rbinnext [1])
  );
  sky130_fd_sc_hd__xnor2_1 _599_ (
    .A(\fifomem.raddr [0]),
    .B(_196_),
    .Y(\rptr_empty.rbinnext [0])
  );
  sky130_fd_sc_hd__and2_0 _600_ (
    .A(\rptr_empty.rbinnext [1]),
    .B(\rptr_empty.rbinnext [0]),
    .X(_207_)
  );
  sky130_fd_sc_hd__xor2_1 _601_ (
    .A(\rptr_empty.rbinnext [1]),
    .B(\rptr_empty.rbinnext [0]),
    .X(\rptr_empty.rgraynext [0])
  );
  sky130_fd_sc_hd__xnor2_1 _602_ (
    .A(\rptr_empty.rq2_wptr [0]),
    .B(\rptr_empty.rgraynext [0]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__xnor2_1 _603_ (
    .A(_204_),
    .B(\rptr_empty.rbinnext [1]),
    .Y(\rptr_empty.rgraynext [1])
  );
  sky130_fd_sc_hd__xnor2_1 _604_ (
    .A(\rptr_empty.rq2_wptr [1]),
    .B(\rptr_empty.rgraynext [1]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand3_1 _605_ (
    .A(_205_),
    .B(_208_),
    .C(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nor3_1 _606_ (
    .A(_203_),
    .B(_206_),
    .C(_210_),
    .Y(\rptr_empty.rempty_val )
  );
  sky130_fd_sc_hd__nand2_1 _607_ (
    .A(\rptr_empty.rbinnext [2]),
    .B(_207_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__xnor2_1 _608_ (
    .A(_204_),
    .B(_207_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__xnor3_1 _609_ (
    .A(\rptr_empty.rbinnext [2]),
    .B(_207_),
    .C(\rptr_empty.rgraynext [0]),
    .X(_213_)
  );
  sky130_fd_sc_hd__or2_0 _610_ (
    .A(\rptr_empty.rq2_wptr [1]),
    .B(_213_),
    .X(_214_)
  );
  sky130_fd_sc_hd__a22oi_1 _611_ (
    .A1(\rptr_empty.rq2_wptr [0]),
    .A2(\rptr_empty.rbinnext [1]),
    .B1(_213_),
    .B2(\rptr_empty.rq2_wptr [1]),
    .Y(_215_)
  );
  sky130_fd_sc_hd__o211ai_1 _612_ (
    .A1(\rptr_empty.rq2_wptr [0]),
    .A2(\rptr_empty.rbinnext [1]),
    .B1(_214_),
    .C1(_215_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nor3b_1 _613_ (
    .A(_202_),
    .B(_204_),
    .C_N(_207_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__xnor2_1 _614_ (
    .A(\rptr_empty.rbinnext [4]),
    .B(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__xnor2_1 _615_ (
    .A(\rptr_empty.rq2_wptr [4]),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__a21o_1 _616_ (
    .A1(_202_),
    .A2(_211_),
    .B1(_217_),
    .X(_220_)
  );
  sky130_fd_sc_hd__xnor3_1 _617_ (
    .A(\rptr_empty.rq2_wptr [2]),
    .B(_212_),
    .C(_220_),
    .X(_221_)
  );
  sky130_fd_sc_hd__xor3_1 _618_ (
    .A(\rptr_empty.rq2_wptr [3]),
    .B(_218_),
    .C(_220_),
    .X(_222_)
  );
  sky130_fd_sc_hd__nor4_1 _619_ (
    .A(_216_),
    .B(_219_),
    .C(_221_),
    .D(_222_),
    .Y(\rptr_empty.arempty_val )
  );
  sky130_fd_sc_hd__dfrtp_1 _620_ (
    .CLK(rclk),
    .D(\rptr_empty.rbinnext [0]),
    .Q(\fifomem.raddr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _621_ (
    .CLK(rclk),
    .D(\rptr_empty.rbinnext [1]),
    .Q(\fifomem.raddr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _622_ (
    .CLK(rclk),
    .D(\rptr_empty.rbinnext [2]),
    .Q(\fifomem.raddr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _623_ (
    .CLK(rclk),
    .D(\rptr_empty.rbinnext [3]),
    .Q(\fifomem.raddr [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _624_ (
    .CLK(rclk),
    .D(\rptr_empty.rgraynext [0]),
    .Q(\rptr_empty.rptr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _625_ (
    .CLK(rclk),
    .D(\rptr_empty.rgraynext [1]),
    .Q(\rptr_empty.rptr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _626_ (
    .CLK(rclk),
    .D(\rptr_empty.rgraynext [2]),
    .Q(\rptr_empty.rptr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _627_ (
    .CLK(rclk),
    .D(\rptr_empty.rgraynext [3]),
    .Q(\rptr_empty.rptr [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _628_ (
    .CLK(rclk),
    .D(\rptr_empty.rbinnext [4]),
    .Q(\rptr_empty.rbin [4]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _629_ (
    .CLK(rclk),
    .D(\rptr_empty.arempty_val ),
    .Q(arempty),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _630_ (
    .CLK(rclk),
    .D(\rptr_empty.rempty_val ),
    .Q(rempty),
    .SET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _631_ (
    .CLK(wclk),
    .D(\rptr_empty.rptr [0]),
    .Q(\sync_r2w.wq1_rptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _632_ (
    .CLK(wclk),
    .D(\rptr_empty.rptr [1]),
    .Q(\sync_r2w.wq1_rptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _633_ (
    .CLK(wclk),
    .D(\rptr_empty.rptr [2]),
    .Q(\sync_r2w.wq1_rptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _634_ (
    .CLK(wclk),
    .D(\rptr_empty.rptr [3]),
    .Q(\sync_r2w.wq1_rptr [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _635_ (
    .CLK(wclk),
    .D(\rptr_empty.rbin [4]),
    .Q(\sync_r2w.wq1_rptr [4]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _636_ (
    .CLK(wclk),
    .D(\sync_r2w.wq1_rptr [0]),
    .Q(\sync_r2w.wq2_rptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _637_ (
    .CLK(wclk),
    .D(\sync_r2w.wq1_rptr [1]),
    .Q(\sync_r2w.wq2_rptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _638_ (
    .CLK(wclk),
    .D(\sync_r2w.wq1_rptr [2]),
    .Q(\sync_r2w.wq2_rptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _639_ (
    .CLK(wclk),
    .D(\sync_r2w.wq1_rptr [3]),
    .Q(\sync_r2w.wq2_rptr [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _640_ (
    .CLK(wclk),
    .D(\sync_r2w.wq1_rptr [4]),
    .Q(\sync_r2w.wq2_rptr [4]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _641_ (
    .CLK(rclk),
    .D(\sync_w2r.wptr [0]),
    .Q(\sync_w2r.rq1_wptr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _642_ (
    .CLK(rclk),
    .D(\sync_w2r.wptr [1]),
    .Q(\sync_w2r.rq1_wptr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _643_ (
    .CLK(rclk),
    .D(\sync_w2r.wptr [2]),
    .Q(\sync_w2r.rq1_wptr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _644_ (
    .CLK(rclk),
    .D(\sync_w2r.wptr [3]),
    .Q(\sync_w2r.rq1_wptr [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _645_ (
    .CLK(rclk),
    .D(\sync_w2r.wptr [4]),
    .Q(\sync_w2r.rq1_wptr [4]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _646_ (
    .CLK(rclk),
    .D(\sync_w2r.rq1_wptr [0]),
    .Q(\rptr_empty.rq2_wptr [0]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _647_ (
    .CLK(rclk),
    .D(\sync_w2r.rq1_wptr [1]),
    .Q(\rptr_empty.rq2_wptr [1]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _648_ (
    .CLK(rclk),
    .D(\sync_w2r.rq1_wptr [2]),
    .Q(\rptr_empty.rq2_wptr [2]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _649_ (
    .CLK(rclk),
    .D(\sync_w2r.rq1_wptr [3]),
    .Q(\rptr_empty.rq2_wptr [3]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _650_ (
    .CLK(rclk),
    .D(\sync_w2r.rq1_wptr [4]),
    .Q(\rptr_empty.rq2_wptr [4]),
    .RESET_B(rrst_n)
  );
  sky130_fd_sc_hd__nand2b_1 _651_ (
    .A_N(wfull),
    .B(winc),
    .Y(_223_)
  );
  sky130_fd_sc_hd__nand3b_1 _652_ (
    .A_N(wfull),
    .B(winc),
    .C(\fifomem.waddr [0]),
    .Y(_224_)
  );
  sky130_fd_sc_hd__xnor2_1 _653_ (
    .A(\fifomem.waddr [0]),
    .B(_223_),
    .Y(\wptr_full.wbinnext [0])
  );
  sky130_fd_sc_hd__and4b_1 _654_ (
    .A_N(wfull),
    .B(\fifomem.waddr [1]),
    .C(winc),
    .D(\fifomem.waddr [0]),
    .X(_225_)
  );
  sky130_fd_sc_hd__nand3_1 _655_ (
    .A(\fifomem.waddr [3]),
    .B(\fifomem.waddr [2]),
    .C(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__xor2_1 _656_ (
    .A(\sync_w2r.wptr [4]),
    .B(_226_),
    .X(_227_)
  );
  sky130_fd_sc_hd__clkinv_1 _657_ (
    .A(_227_),
    .Y(\wptr_full.wbinnext [4])
  );
  sky130_fd_sc_hd__a21o_1 _658_ (
    .A1(\fifomem.waddr [2]),
    .A2(_225_),
    .B1(\fifomem.waddr [3]),
    .X(_228_)
  );
  sky130_fd_sc_hd__nand2_1 _659_ (
    .A(_226_),
    .B(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__clkinv_1 _660_ (
    .A(_229_),
    .Y(\wptr_full.wbinnext [3])
  );
  sky130_fd_sc_hd__xor2_1 _661_ (
    .A(_227_),
    .B(_229_),
    .X(\wptr_full.wgraynext [3])
  );
  sky130_fd_sc_hd__xnor2_1 _662_ (
    .A(\sync_r2w.wq2_rptr [3]),
    .B(\wptr_full.wgraynext [3]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__xnor2_1 _663_ (
    .A(\fifomem.waddr [2]),
    .B(_225_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__clkinv_1 _664_ (
    .A(_231_),
    .Y(\wptr_full.wbinnext [2])
  );
  sky130_fd_sc_hd__xnor2_1 _665_ (
    .A(_229_),
    .B(\wptr_full.wbinnext [2]),
    .Y(\wptr_full.wgraynext [2])
  );
  sky130_fd_sc_hd__xnor2_1 _666_ (
    .A(\sync_r2w.wq2_rptr [2]),
    .B(\wptr_full.wgraynext [2]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__xor2_1 _667_ (
    .A(\sync_r2w.wq2_rptr [4]),
    .B(_227_),
    .X(_233_)
  );
  sky130_fd_sc_hd__xnor2_1 _668_ (
    .A(\fifomem.waddr [1]),
    .B(_224_),
    .Y(\wptr_full.wbinnext [1])
  );
  sky130_fd_sc_hd__and2_0 _669_ (
    .A(\wptr_full.wbinnext [0]),
    .B(\wptr_full.wbinnext [1]),
    .X(_234_)
  );
  sky130_fd_sc_hd__xor2_1 _670_ (
    .A(\wptr_full.wbinnext [0]),
    .B(\wptr_full.wbinnext [1]),
    .X(\wptr_full.wgraynext [0])
  );
  sky130_fd_sc_hd__xnor2_1 _671_ (
    .A(\sync_r2w.wq2_rptr [0]),
    .B(\wptr_full.wgraynext [0]),
    .Y(_235_)
  );
  sky130_fd_sc_hd__xnor2_1 _672_ (
    .A(_231_),
    .B(\wptr_full.wbinnext [1]),
    .Y(\wptr_full.wgraynext [1])
  );
  sky130_fd_sc_hd__xnor2_1 _673_ (
    .A(\sync_r2w.wq2_rptr [1]),
    .B(\wptr_full.wgraynext [1]),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand3_1 _674_ (
    .A(_232_),
    .B(_235_),
    .C(_236_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor3_1 _675_ (
    .A(_230_),
    .B(_233_),
    .C(_237_),
    .Y(\wptr_full.wfull_val )
  );
  sky130_fd_sc_hd__nand2_1 _676_ (
    .A(\wptr_full.wbinnext [2]),
    .B(_234_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__xnor2_1 _677_ (
    .A(_231_),
    .B(_234_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__xnor3_1 _678_ (
    .A(\wptr_full.wbinnext [2]),
    .B(_234_),
    .C(\wptr_full.wgraynext [0]),
    .X(_240_)
  );
  sky130_fd_sc_hd__xor2_1 _679_ (
    .A(\sync_r2w.wq2_rptr [0]),
    .B(\wptr_full.wbinnext [1]),
    .X(_241_)
  );
  sky130_fd_sc_hd__o21ai_0 _680_ (
    .A1(\sync_r2w.wq2_rptr [1]),
    .A2(_240_),
    .B1(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a21o_1 _681_ (
    .A1(\sync_r2w.wq2_rptr [1]),
    .A2(_240_),
    .B1(_242_),
    .X(_243_)
  );
  sky130_fd_sc_hd__nor3b_1 _682_ (
    .A(_229_),
    .B(_231_),
    .C_N(_234_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__xnor2_1 _683_ (
    .A(\wptr_full.wbinnext [4]),
    .B(_244_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__xor2_1 _684_ (
    .A(\sync_r2w.wq2_rptr [4]),
    .B(_245_),
    .X(_246_)
  );
  sky130_fd_sc_hd__a21o_1 _685_ (
    .A1(_229_),
    .A2(_238_),
    .B1(_244_),
    .X(_247_)
  );
  sky130_fd_sc_hd__xnor3_1 _686_ (
    .A(\sync_r2w.wq2_rptr [2]),
    .B(_239_),
    .C(_247_),
    .X(_248_)
  );
  sky130_fd_sc_hd__xnor3_1 _687_ (
    .A(\sync_r2w.wq2_rptr [3]),
    .B(_245_),
    .C(_247_),
    .X(_249_)
  );
  sky130_fd_sc_hd__nor4_1 _688_ (
    .A(_243_),
    .B(_246_),
    .C(_248_),
    .D(_249_),
    .Y(\wptr_full.awfull_val )
  );
  sky130_fd_sc_hd__dfrtp_1 _689_ (
    .CLK(wclk),
    .D(\wptr_full.wbinnext [0]),
    .Q(\fifomem.waddr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _690_ (
    .CLK(wclk),
    .D(\wptr_full.wbinnext [1]),
    .Q(\fifomem.waddr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _691_ (
    .CLK(wclk),
    .D(\wptr_full.wbinnext [2]),
    .Q(\fifomem.waddr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _692_ (
    .CLK(wclk),
    .D(\wptr_full.wbinnext [3]),
    .Q(\fifomem.waddr [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _693_ (
    .CLK(wclk),
    .D(\wptr_full.wgraynext [0]),
    .Q(\sync_w2r.wptr [0]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _694_ (
    .CLK(wclk),
    .D(\wptr_full.wgraynext [1]),
    .Q(\sync_w2r.wptr [1]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _695_ (
    .CLK(wclk),
    .D(\wptr_full.wgraynext [2]),
    .Q(\sync_w2r.wptr [2]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _696_ (
    .CLK(wclk),
    .D(\wptr_full.wgraynext [3]),
    .Q(\sync_w2r.wptr [3]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _697_ (
    .CLK(wclk),
    .D(\wptr_full.wbinnext [4]),
    .Q(\sync_w2r.wptr [4]),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _698_ (
    .CLK(wclk),
    .D(\wptr_full.awfull_val ),
    .Q(awfull),
    .RESET_B(wrst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _699_ (
    .CLK(wclk),
    .D(\wptr_full.wfull_val ),
    .Q(wfull),
    .RESET_B(wrst_n)
  );
  assign \rptr_empty.rptr [4] = \rptr_empty.rbin [4];
  assign \rptr_empty.rgraynext [4] = \rptr_empty.rbinnext [4];
  assign \rptr_empty.rbin [3:0] = \fifomem.raddr ;
  assign \wptr_full.wgraynext [4] = \wptr_full.wbinnext [4];
endmodule
